### ISSUE TITLE
Compatibility issue with DRF 3.14.0

### ISSUE THREAD

**Issue by tonioo** [royhzq/djagger#10]
NullBooleanField was removed starting from DRF 3.14.0

So, I encounter this issue with current djagger version:

```python
Traceback (most recent call last):
  File "/home/tonio/.virtualenvs/backend-VcZ5AJ-y/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/tonio/.virtualenvs/backend-VcZ5AJ-y/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/tonio/.virtualenvs/backend-VcZ5AJ-y/lib/python3.7/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/tonio/projets/pro/SubstancesActives/djagger/djagger/views.py", line 17, in open_api_json
    document = Document.generate(**doc_settings)
  File "/home/tonio/projets/pro/SubstancesActives/djagger/djagger/openapi.py", line 956, in generate
    path = Path.create(view)
  File "/home/tonio/projets/pro/SubstancesActives/djagger/djagger/openapi.py", line 826, in create
    operation = Operation._from(view_func, http_method)
  File "/home/tonio/projets/pro/SubstancesActives/djagger/djagger/openapi.py", line 768, in _from
    operation._extract_responses(view, http_method)
  File "/home/tonio/projets/pro/SubstancesActives/djagger/djagger/openapi.py", line 639, in _extract_responses
    responses = {"200": Response._from(response_schema)}
  File "/home/tonio/projets/pro/SubstancesActives/djagger/djagger/openapi.py", line 399, in _from
    content={content_type: MediaType._from(model)},
  File "/home/tonio/projets/pro/SubstancesActives/djagger/djagger/openapi.py", line 267, in _from
    model = SerializerConverter(s=model).to_model()
  File "/home/tonio/projets/pro/SubstancesActives/djagger/djagger/serializers.py", line 252, in to_model
    return self.from_serializer(self.s())
  File "/home/tonio/projets/pro/SubstancesActives/djagger/djagger/serializers.py", line 218, in from_serializer
    t = cls.infer_field_type(field, field_name)
  File "/home/tonio/projets/pro/SubstancesActives/djagger/djagger/serializers.py", line 98, in infer_field_type
    fields.NullBooleanField: bool,
AttributeError: module 'rest_framework.fields' has no attribute 'NullBooleanField'
```

**Comment by royhzq** [comment]
@tonioo thanks for this. I'll put in the fix and review the other PR in the next few days.

**Comment by tonioo** [comment]
@royhzq great! Are you planning a new release soon?

**Comment by royhzq** [comment]
@tonioo yes, I'll do a few more checks and probably release 1.1.4 this by the end of the week.

**Comment by royhzq** [comment]
@tonioo 1.1.4 released. Thanks for the contributions.
